/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userValidation = require('./user.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userAddressValidation = require('./userAddress.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userDashboardConfigValidation = require('./userDashboardConfig.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.productCategoriesValidation = require('./productCategories.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.storeValidation = require('./store.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.storeAddressValidation = require('./storeAddress.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.businessCategoryValidation = require('./businessCategory.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.sellerUserValidation = require('./sellerUser.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.pickupAddressValidation = require('./pickupAddress.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.bankDetailsValidation = require('./bankDetails.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.productValidation = require('./product.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.productTypeValidation = require('./productType.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.productBrandValidation = require('./productBrand.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.productVarientsValidation = require('./productVarients.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.productVarientByProductIdValidation = require('./productVarientByProductId.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userlikeValidation = require('./userlike.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.recentlyViewedValidation = require('./recentlyViewed.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.reviewValidation = require('./review.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.cartValidation = require('./cart.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.coupanValidation = require('./coupan.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userCoupanValidation = require('./userCoupan.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userWishlistValidation = require('./userWishlist.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.reviewReplyThreadValidation = require('./reviewReplyThread.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.orderValidation = require('./order.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.paymentValidation = require('./payment.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.sellerPolicyValidation = require('./sellerPolicy.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.inventoryValidation = require('./inventory.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.inventoryAddressValidation = require('./inventoryAddress.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.testValidation = require('./test.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.storeNotificationValidation = require('./storeNotification.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.storeConfigValidation = require('./storeConfig.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.authValidation = require('./auth.validation');
