import express from 'express';
import userRoutes from './v1/user/user.route';
import userAddressRoutes from './v1/userAddress/userAddress.route';
import userDashboardConfigRoutes from './v1/userDashboardConfig/userDashboardConfig.route';
import productCategoriesRoutes from './v1/productCategories/productCategories.route';
import storeRoutes from './v1/store/store.route';
import storeAddressRoutes from './v1/storeAddress/storeAddress.route';
import businessCategoryRoutes from './v1/businessCategory/businessCategory.route';
import sellerUserRoutes from './v1/sellerUser/sellerUser.route';
import pickupAddressRoutes from './v1/pickupAddress/pickupAddress.route';
import bankDetailsRoutes from './v1/bankDetails/bankDetails.route';
import productRoutes from './v1/product/product.route';
import productTypeRoutes from './v1/productType/productType.route';
import productBrandRoutes from './v1/productBrand/productBrand.route';
import productVarientsRoutes from './v1/productVarients/productVarients.route';
import productVarientByProductIdRoutes from './v1/productVarientByProductId/productVarientByProductId.route';
import userlikeRoutes from './v1/userlike/userlike.route';
import recentlyViewedRoutes from './v1/recentlyViewed/recentlyViewed.route';
import reviewRoutes from './v1/review/review.route';
import cartRoutes from './v1/cart/cart.route';
import coupanRoutes from './v1/coupan/coupan.route';
import userCoupanRoutes from './v1/userCoupan/userCoupan.route';
import userWishlistRoutes from './v1/userWishlist/userWishlist.route';
import reviewReplyThreadRoutes from './v1/reviewReplyThread/reviewReplyThread.route';
import orderRoutes from './v1/order/order.route';
import paymentRoutes from './v1/payment/payment.route';
import sellerPolicyRoutes from './v1/sellerPolicy/sellerPolicy.route';
import inventoryRoutes from './v1/inventory/inventory.route';
import inventoryAddressRoutes from './v1/inventoryAddress/inventoryAddress.route';
import testRoutes from './v1/test/test.route';
import storeNotificationRoutes from './v1/storeNotification/storeNotification.route';
import storeConfigRoutes from './v1/storeConfig/storeConfig.route';

const router = express.Router();
router.use('/user', userRoutes);
router.use('/userAddress', userAddressRoutes);
router.use('/userDashboardConfig', userDashboardConfigRoutes);
router.use('/productCategories', productCategoriesRoutes);
router.use('/store', storeRoutes);
router.use('/storeAddress', storeAddressRoutes);
router.use('/businessCategory', businessCategoryRoutes);
router.use('/sellerUser', sellerUserRoutes);
router.use('/pickupAddress', pickupAddressRoutes);
router.use('/bankDetails', bankDetailsRoutes);
router.use('/product', productRoutes);
router.use('/productType', productTypeRoutes);
router.use('/productBrand', productBrandRoutes);
router.use('/productVarients', productVarientsRoutes);
router.use('/productVarientByProductId', productVarientByProductIdRoutes);
router.use('/userlike', userlikeRoutes);
router.use('/recentlyViewed', recentlyViewedRoutes);
router.use('/review', reviewRoutes);
router.use('/cart', cartRoutes);
router.use('/coupan', coupanRoutes);
router.use('/userCoupan', userCoupanRoutes);
router.use('/userWishlist', userWishlistRoutes);
router.use('/reviewReplyThread', reviewReplyThreadRoutes);
router.use('/order', orderRoutes);
router.use('/payment', paymentRoutes);
router.use('/sellerPolicy', sellerPolicyRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/inventoryAddress', inventoryAddressRoutes);
router.use('/test', testRoutes);
router.use('/storeNotification', storeNotificationRoutes);
router.use('/storeConfig', storeConfigRoutes);
module.exports = router;
