/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { BusinessCategory } from 'models';

export async function getBusinessCategoryById(id, options = {}) {
  const businessCategory = await BusinessCategory.findById(id, options.projection, options);
  return businessCategory;
}

export async function getOne(query, options = {}) {
  const businessCategory = await BusinessCategory.findOne(query, options.projection, options);
  return businessCategory;
}

export async function getBusinessCategoryList(filter, options = {}) {
  const businessCategory = await BusinessCategory.find(filter, options.projection, options);
  return businessCategory;
}

export async function getBusinessCategoryListWithPagination(filter, options = {}) {
  const businessCategory = await BusinessCategory.paginate(filter, options);
  return businessCategory;
}

export async function createBusinessCategory(body, options = {}) {
  const businessCategory = await BusinessCategory.create(body);
  return businessCategory;
}

export async function updateBusinessCategory(filter, body, options = {}) {
  const businessCategory = await BusinessCategory.findOneAndUpdate(filter, body, options);
  return businessCategory;
}

export async function updateManyBusinessCategory(filter, body, options = {}) {
  const businessCategory = await BusinessCategory.updateMany(filter, body, options);
  return businessCategory;
}

export async function removeBusinessCategory(filter) {
  const businessCategory = await BusinessCategory.findOneAndRemove(filter);
  return businessCategory;
}

export async function removeManyBusinessCategory(filter) {
  const businessCategory = await BusinessCategory.deleteMany(filter);
  return businessCategory;
}

export async function aggregateBusinessCategory(query) {
  const businessCategory = await BusinessCategory.aggregate(query);
  return businessCategory;
}

export async function aggregateBusinessCategoryWithPagination(query, options = {}) {
  const aggregate = BusinessCategory.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const businessCategory = await BusinessCategory.aggregatePaginate(aggregate, options);
  return businessCategory;
}
