/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { Coupan } from 'models';

export async function getCoupanById(id, options = {}) {
  const coupan = await Coupan.findById(id, options.projection, options);
  return coupan;
}

export async function getOne(query, options = {}) {
  const coupan = await Coupan.findOne(query, options.projection, options);
  return coupan;
}

export async function getCoupanList(filter, options = {}) {
  const coupan = await Coupan.find(filter, options.projection, options);
  return coupan;
}

export async function getCoupanListWithPagination(filter, options = {}) {
  const coupan = await Coupan.paginate(filter, options);
  return coupan;
}

export async function createCoupan(body, options = {}) {
  const coupan = await Coupan.create(body);
  return coupan;
}

export async function updateCoupan(filter, body, options = {}) {
  const coupan = await Coupan.findOneAndUpdate(filter, body, options);
  return coupan;
}

export async function updateManyCoupan(filter, body, options = {}) {
  const coupan = await Coupan.updateMany(filter, body, options);
  return coupan;
}

export async function removeCoupan(filter) {
  const coupan = await Coupan.findOneAndRemove(filter);
  return coupan;
}

export async function removeManyCoupan(filter) {
  const coupan = await Coupan.deleteMany(filter);
  return coupan;
}

export async function aggregateCoupan(query) {
  const coupan = await Coupan.aggregate(query);
  return coupan;
}

export async function aggregateCoupanWithPagination(query, options = {}) {
  const aggregate = Coupan.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const coupan = await Coupan.aggregatePaginate(aggregate, options);
  return coupan;
}
