/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { InventoryAddress } from 'models';

export async function getInventoryAddressById(id, options = {}) {
  const inventoryAddress = await InventoryAddress.findById(id, options.projection, options);
  return inventoryAddress;
}

export async function getOne(query, options = {}) {
  const inventoryAddress = await InventoryAddress.findOne(query, options.projection, options);
  return inventoryAddress;
}

export async function getInventoryAddressList(filter, options = {}) {
  const inventoryAddress = await InventoryAddress.find(filter, options.projection, options);
  return inventoryAddress;
}

export async function getInventoryAddressListWithPagination(filter, options = {}) {
  const inventoryAddress = await InventoryAddress.paginate(filter, options);
  return inventoryAddress;
}

export async function createInventoryAddress(body, options = {}) {
  const inventoryAddress = await InventoryAddress.create(body);
  return inventoryAddress;
}

export async function updateInventoryAddress(filter, body, options = {}) {
  const inventoryAddress = await InventoryAddress.findOneAndUpdate(filter, body, options);
  return inventoryAddress;
}

export async function updateManyInventoryAddress(filter, body, options = {}) {
  const inventoryAddress = await InventoryAddress.updateMany(filter, body, options);
  return inventoryAddress;
}

export async function removeInventoryAddress(filter) {
  const inventoryAddress = await InventoryAddress.findOneAndRemove(filter);
  return inventoryAddress;
}

export async function removeManyInventoryAddress(filter) {
  const inventoryAddress = await InventoryAddress.deleteMany(filter);
  return inventoryAddress;
}

export async function aggregateInventoryAddress(query) {
  const inventoryAddress = await InventoryAddress.aggregate(query);
  return inventoryAddress;
}

export async function aggregateInventoryAddressWithPagination(query, options = {}) {
  const aggregate = InventoryAddress.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const inventoryAddress = await InventoryAddress.aggregatePaginate(aggregate, options);
  return inventoryAddress;
}
