/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Order, Payment } from 'models';

export async function getOrderById(id, options = {}) {
  const order = await Order.findById(id, options.projection, options);
  return order;
}

export async function getOne(query, options = {}) {
  const order = await Order.findOne(query, options.projection, options);
  return order;
}

export async function getOrderList(filter, options = {}) {
  const order = await Order.find(filter, options.projection, options);
  return order;
}

export async function getOrderListWithPagination(filter, options = {}) {
  const order = await Order.paginate(filter, options);
  return order;
}

export async function createOrder(body, options = {}) {
  if (body.paymentId) {
    const paymentId = await Payment.findOne({ _id: body.paymentId });
    if (!paymentId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field paymentId is not valid');
    }
  }
  const order = await Order.create(body);
  return order;
}

export async function updateOrder(filter, body, options = {}) {
  if (body.paymentId) {
    const paymentId = await Payment.findOne({ _id: body.paymentId });
    if (!paymentId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field paymentId is not valid');
    }
  }
  const order = await Order.findOneAndUpdate(filter, body, options);
  return order;
}

export async function updateManyOrder(filter, body, options = {}) {
  const order = await Order.updateMany(filter, body, options);
  return order;
}

export async function removeOrder(filter) {
  const order = await Order.findOneAndRemove(filter);
  return order;
}

export async function removeManyOrder(filter) {
  const order = await Order.deleteMany(filter);
  return order;
}

export async function aggregateOrder(query) {
  const order = await Order.aggregate(query);
  return order;
}

export async function aggregateOrderWithPagination(query, options = {}) {
  const aggregate = Order.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const order = await Order.aggregatePaginate(aggregate, options);
  return order;
}
