/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { PickupAddress, Store } from 'models';

export async function getPickupAddressById(id, options = {}) {
  const pickupAddress = await PickupAddress.findById(id, options.projection, options);
  return pickupAddress;
}

export async function getOne(query, options = {}) {
  const pickupAddress = await PickupAddress.findOne(query, options.projection, options);
  return pickupAddress;
}

export async function getPickupAddressList(filter, options = {}) {
  const pickupAddress = await PickupAddress.find(filter, options.projection, options);
  return pickupAddress;
}

export async function getPickupAddressListWithPagination(filter, options = {}) {
  const pickupAddress = await PickupAddress.paginate(filter, options);
  return pickupAddress;
}

export async function createPickupAddress(body, options = {}) {
  if (body.storeId) {
    const storeId = await Store.findOne({ _id: body.storeId });
    if (!storeId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field storeId is not valid');
    }
  }
  const pickupAddress = await PickupAddress.create(body);
  return pickupAddress;
}

export async function updatePickupAddress(filter, body, options = {}) {
  if (body.storeId) {
    const storeId = await Store.findOne({ _id: body.storeId });
    if (!storeId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field storeId is not valid');
    }
  }
  const pickupAddress = await PickupAddress.findOneAndUpdate(filter, body, options);
  return pickupAddress;
}

export async function updateManyPickupAddress(filter, body, options = {}) {
  const pickupAddress = await PickupAddress.updateMany(filter, body, options);
  return pickupAddress;
}

export async function removePickupAddress(filter) {
  const pickupAddress = await PickupAddress.findOneAndRemove(filter);
  return pickupAddress;
}

export async function removeManyPickupAddress(filter) {
  const pickupAddress = await PickupAddress.deleteMany(filter);
  return pickupAddress;
}

export async function aggregatePickupAddress(query) {
  const pickupAddress = await PickupAddress.aggregate(query);
  return pickupAddress;
}

export async function aggregatePickupAddressWithPagination(query, options = {}) {
  const aggregate = PickupAddress.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const pickupAddress = await PickupAddress.aggregatePaginate(aggregate, options);
  return pickupAddress;
}
