/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { ProductBrand } from 'models';
import { logger } from '../config/logger';

export async function getProductBrandById(id, options = {}) {
  const productBrand = await ProductBrand.findById(id, options.projection, options);
  return productBrand;
}

export async function getOne(query, options = {}) {
  const productBrand = await ProductBrand.findOne(query, options.projection, options);
  return productBrand;
}

export async function getProductBrandList(filter, options = {}) {
  const productBrand = await ProductBrand.find(filter, options.projection, options);
  return productBrand;
}

export async function getProductBrandListWithPagination(filter, options = {}) {
  const productBrand = await ProductBrand.paginate(filter, options);
  return productBrand;
}

export async function createProductBrand(body, options = {}) {
  try {
    const productBrand = await ProductBrand.create(body);
    return productBrand;
  } catch (error) {
    logger.error('error in creating productBrand:', error);
    if (error.name === 'MongoError' && error.code === 11000) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'You are trying to create duplicate entry!');
    } else {
      throw new ApiError(httpStatus.BAD_REQUEST, error.message);
    }
  }
}

export async function updateProductBrand(filter, body, options = {}) {
  try {
    const productBrand = await ProductBrand.findOneAndUpdate(filter, body, options);
    return productBrand;
  } catch (error) {
    logger.error('error in creating productBrand:', error);
    if (error.name === 'MongoError' && error.code === 11000) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'You are trying to create duplicate entry!');
    } else {
      throw new ApiError(httpStatus.BAD_REQUEST, error.message);
    }
  }
}

export async function updateManyProductBrand(filter, body, options = {}) {
  try {
    const productBrand = await ProductBrand.updateMany(filter, body, options);
    return productBrand;
  } catch (error) {
    logger.error('error in creating productBrand:', error);
    if (error.name === 'MongoError' && error.code === 11000) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'You are trying to create duplicate entry!');
    } else {
      throw new ApiError(httpStatus.BAD_REQUEST, error.message);
    }
  }
}

export async function removeProductBrand(filter) {
  const productBrand = await ProductBrand.findOneAndRemove(filter);
  return productBrand;
}

export async function removeManyProductBrand(filter) {
  const productBrand = await ProductBrand.deleteMany(filter);
  return productBrand;
}

export async function aggregateProductBrand(query) {
  const productBrand = await ProductBrand.aggregate(query);
  return productBrand;
}

export async function aggregateProductBrandWithPagination(query, options = {}) {
  const aggregate = ProductBrand.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const productBrand = await ProductBrand.aggregatePaginate(aggregate, options);
  return productBrand;
}
