/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { ProductVarients, ProductCategories } from 'models';

export async function getProductVarientsById(id, options = {}) {
  const productVarients = await ProductVarients.findById(id, options.projection, options);
  return productVarients;
}

export async function getOne(query, options = {}) {
  const productVarients = await ProductVarients.findOne(query, options.projection, options);
  return productVarients;
}

export async function getProductVarientsList(filter, options = {}) {
  const productVarients = await ProductVarients.find(filter, options.projection, options);
  return productVarients;
}

export async function getProductVarientsListWithPagination(filter, options = {}) {
  const productVarients = await ProductVarients.paginate(filter, options);
  return productVarients;
}

export async function createProductVarients(body, options = {}) {
  if (body.productCategoryId) {
    const productCategoryId = await ProductCategories.findOne({ _id: body.productCategoryId });
    if (!productCategoryId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productCategoryId is not valid');
    }
  }
  const productVarients = await ProductVarients.create(body);
  return productVarients;
}

export async function updateProductVarients(filter, body, options = {}) {
  if (body.productCategoryId) {
    const productCategoryId = await ProductCategories.findOne({ _id: body.productCategoryId });
    if (!productCategoryId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productCategoryId is not valid');
    }
  }
  const productVarients = await ProductVarients.findOneAndUpdate(filter, body, options);
  return productVarients;
}

export async function updateManyProductVarients(filter, body, options = {}) {
  const productVarients = await ProductVarients.updateMany(filter, body, options);
  return productVarients;
}

export async function removeProductVarients(filter) {
  const productVarients = await ProductVarients.findOneAndRemove(filter);
  return productVarients;
}

export async function removeManyProductVarients(filter) {
  const productVarients = await ProductVarients.deleteMany(filter);
  return productVarients;
}

export async function aggregateProductVarients(query) {
  const productVarients = await ProductVarients.aggregate(query);
  return productVarients;
}

export async function aggregateProductVarientsWithPagination(query, options = {}) {
  const aggregate = ProductVarients.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const productVarients = await ProductVarients.aggregatePaginate(aggregate, options);
  return productVarients;
}
