/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { ProductType } from 'models';

export async function getProductTypeById(id, options = {}) {
  const productType = await ProductType.findById(id, options.projection, options);
  return productType;
}

export async function getOne(query, options = {}) {
  const productType = await ProductType.findOne(query, options.projection, options);
  return productType;
}

export async function getProductTypeList(filter, options = {}) {
  const productType = await ProductType.find(filter, options.projection, options);
  return productType;
}

export async function getProductTypeListWithPagination(filter, options = {}) {
  const productType = await ProductType.paginate(filter, options);
  return productType;
}

export async function createProductType(body, options = {}) {
  const productType = await ProductType.create(body);
  return productType;
}

export async function updateProductType(filter, body, options = {}) {
  const productType = await ProductType.findOneAndUpdate(filter, body, options);
  return productType;
}

export async function updateManyProductType(filter, body, options = {}) {
  const productType = await ProductType.updateMany(filter, body, options);
  return productType;
}

export async function removeProductType(filter) {
  const productType = await ProductType.findOneAndRemove(filter);
  return productType;
}

export async function removeManyProductType(filter) {
  const productType = await ProductType.deleteMany(filter);
  return productType;
}

export async function aggregateProductType(query) {
  const productType = await ProductType.aggregate(query);
  return productType;
}

export async function aggregateProductTypeWithPagination(query, options = {}) {
  const aggregate = ProductType.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const productType = await ProductType.aggregatePaginate(aggregate, options);
  return productType;
}
