/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { RecentlyViewed, Product } from 'models';

export async function getRecentlyViewedById(id, options = {}) {
  const recentlyViewed = await RecentlyViewed.findById(id, options.projection, options);
  return recentlyViewed;
}

export async function getOne(query, options = {}) {
  const recentlyViewed = await RecentlyViewed.findOne(query, options.projection, options);
  return recentlyViewed;
}

export async function getRecentlyViewedList(filter, options = {}) {
  const recentlyViewed = await RecentlyViewed.find(filter, options.projection, options);
  return recentlyViewed;
}

export async function getRecentlyViewedListWithPagination(filter, options = {}) {
  const recentlyViewed = await RecentlyViewed.paginate(filter, options);
  return recentlyViewed;
}

export async function createRecentlyViewed(body, options = {}) {
  if (body.productId) {
    const productId = await Product.findOne({ _id: body.productId });
    if (!productId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productId is not valid');
    }
  }
  const recentlyViewed = await RecentlyViewed.create(body);
  return recentlyViewed;
}

export async function updateRecentlyViewed(filter, body, options = {}) {
  if (body.productId) {
    const productId = await Product.findOne({ _id: body.productId });
    if (!productId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productId is not valid');
    }
  }
  const recentlyViewed = await RecentlyViewed.findOneAndUpdate(filter, body, options);
  return recentlyViewed;
}

export async function updateManyRecentlyViewed(filter, body, options = {}) {
  const recentlyViewed = await RecentlyViewed.updateMany(filter, body, options);
  return recentlyViewed;
}

export async function removeRecentlyViewed(filter) {
  const recentlyViewed = await RecentlyViewed.findOneAndRemove(filter);
  return recentlyViewed;
}

export async function removeManyRecentlyViewed(filter) {
  const recentlyViewed = await RecentlyViewed.deleteMany(filter);
  return recentlyViewed;
}

export async function aggregateRecentlyViewed(query) {
  const recentlyViewed = await RecentlyViewed.aggregate(query);
  return recentlyViewed;
}

export async function aggregateRecentlyViewedWithPagination(query, options = {}) {
  const aggregate = RecentlyViewed.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const recentlyViewed = await RecentlyViewed.aggregatePaginate(aggregate, options);
  return recentlyViewed;
}
