/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { ReviewReplyThread, Review, SellerUser } from 'models';

export async function getReviewReplyThreadById(id, options = {}) {
  const reviewReplyThread = await ReviewReplyThread.findById(id, options.projection, options);
  return reviewReplyThread;
}

export async function getOne(query, options = {}) {
  const reviewReplyThread = await ReviewReplyThread.findOne(query, options.projection, options);
  return reviewReplyThread;
}

export async function getReviewReplyThreadList(filter, options = {}) {
  const reviewReplyThread = await ReviewReplyThread.find(filter, options.projection, options);
  return reviewReplyThread;
}

export async function getReviewReplyThreadListWithPagination(filter, options = {}) {
  const reviewReplyThread = await ReviewReplyThread.paginate(filter, options);
  return reviewReplyThread;
}

export async function createReviewReplyThread(body, options = {}) {
  if (body.reviewMessageId) {
    const reviewMessageId = await Review.findOne({ _id: body.reviewMessageId });
    if (!reviewMessageId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field reviewMessageId is not valid');
    }
  }
  if (body.storeUserId) {
    const storeUserId = await SellerUser.findOne({ _id: body.storeUserId });
    if (!storeUserId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field storeUserId is not valid');
    }
  }
  const reviewReplyThread = await ReviewReplyThread.create(body);
  return reviewReplyThread;
}

export async function updateReviewReplyThread(filter, body, options = {}) {
  if (body.reviewMessageId) {
    const reviewMessageId = await Review.findOne({ _id: body.reviewMessageId });
    if (!reviewMessageId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field reviewMessageId is not valid');
    }
  }
  if (body.storeUserId) {
    const storeUserId = await SellerUser.findOne({ _id: body.storeUserId });
    if (!storeUserId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field storeUserId is not valid');
    }
  }
  const reviewReplyThread = await ReviewReplyThread.findOneAndUpdate(filter, body, options);
  return reviewReplyThread;
}

export async function updateManyReviewReplyThread(filter, body, options = {}) {
  const reviewReplyThread = await ReviewReplyThread.updateMany(filter, body, options);
  return reviewReplyThread;
}

export async function removeReviewReplyThread(filter) {
  const reviewReplyThread = await ReviewReplyThread.findOneAndRemove(filter);
  return reviewReplyThread;
}

export async function removeManyReviewReplyThread(filter) {
  const reviewReplyThread = await ReviewReplyThread.deleteMany(filter);
  return reviewReplyThread;
}

export async function aggregateReviewReplyThread(query) {
  const reviewReplyThread = await ReviewReplyThread.aggregate(query);
  return reviewReplyThread;
}

export async function aggregateReviewReplyThreadWithPagination(query, options = {}) {
  const aggregate = ReviewReplyThread.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const reviewReplyThread = await ReviewReplyThread.aggregatePaginate(aggregate, options);
  return reviewReplyThread;
}
