/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { SellerUser } from 'models';
import { logger } from '../config/logger';

export async function getSellerUserById(id, options = {}) {
  const sellerUser = await SellerUser.findById(id, options.projection, options);
  return sellerUser;
}

export async function getOne(query, options = {}) {
  const sellerUser = await SellerUser.findOne(query, options.projection, options);
  return sellerUser;
}

export async function getSellerUserList(filter, options = {}) {
  const sellerUser = await SellerUser.find(filter, options.projection, options);
  return sellerUser;
}

export async function getSellerUserListWithPagination(filter, options = {}) {
  const sellerUser = await SellerUser.paginate(filter, options);
  return sellerUser;
}

export async function createSellerUser(body, options = {}) {
  try {
    const sellerUser = await SellerUser.create(body);
    return sellerUser;
  } catch (error) {
    logger.error('error in creating sellerUser:', error);
    if (error.name === 'MongoError' && error.code === 11000) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'You are trying to create duplicate entry!');
    } else {
      throw new ApiError(httpStatus.BAD_REQUEST, error.message);
    }
  }
}

export async function updateSellerUser(filter, body, options = {}) {
  try {
    const sellerUser = await SellerUser.findOneAndUpdate(filter, body, options);
    return sellerUser;
  } catch (error) {
    logger.error('error in creating sellerUser:', error);
    if (error.name === 'MongoError' && error.code === 11000) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'You are trying to create duplicate entry!');
    } else {
      throw new ApiError(httpStatus.BAD_REQUEST, error.message);
    }
  }
}

export async function updateManySellerUser(filter, body, options = {}) {
  try {
    const sellerUser = await SellerUser.updateMany(filter, body, options);
    return sellerUser;
  } catch (error) {
    logger.error('error in creating sellerUser:', error);
    if (error.name === 'MongoError' && error.code === 11000) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'You are trying to create duplicate entry!');
    } else {
      throw new ApiError(httpStatus.BAD_REQUEST, error.message);
    }
  }
}

export async function removeSellerUser(filter) {
  const sellerUser = await SellerUser.findOneAndRemove(filter);
  return sellerUser;
}

export async function removeManySellerUser(filter) {
  const sellerUser = await SellerUser.deleteMany(filter);
  return sellerUser;
}

export async function aggregateSellerUser(query) {
  const sellerUser = await SellerUser.aggregate(query);
  return sellerUser;
}

export async function aggregateSellerUserWithPagination(query, options = {}) {
  const aggregate = SellerUser.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const sellerUser = await SellerUser.aggregatePaginate(aggregate, options);
  return sellerUser;
}
