/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { StoreConfig } from 'models';

export async function getStoreConfigById(id, options = {}) {
  const storeConfig = await StoreConfig.findById(id, options.projection, options);
  return storeConfig;
}

export async function getOne(query, options = {}) {
  const storeConfig = await StoreConfig.findOne(query, options.projection, options);
  return storeConfig;
}

export async function getStoreConfigList(filter, options = {}) {
  const storeConfig = await StoreConfig.find(filter, options.projection, options);
  return storeConfig;
}

export async function getStoreConfigListWithPagination(filter, options = {}) {
  const storeConfig = await StoreConfig.paginate(filter, options);
  return storeConfig;
}

export async function createStoreConfig(body, options = {}) {
  const storeConfig = await StoreConfig.create(body);
  return storeConfig;
}

export async function updateStoreConfig(filter, body, options = {}) {
  const storeConfig = await StoreConfig.findOneAndUpdate(filter, body, options);
  return storeConfig;
}

export async function updateManyStoreConfig(filter, body, options = {}) {
  const storeConfig = await StoreConfig.updateMany(filter, body, options);
  return storeConfig;
}

export async function removeStoreConfig(filter) {
  const storeConfig = await StoreConfig.findOneAndRemove(filter);
  return storeConfig;
}

export async function removeManyStoreConfig(filter) {
  const storeConfig = await StoreConfig.deleteMany(filter);
  return storeConfig;
}

export async function aggregateStoreConfig(query) {
  const storeConfig = await StoreConfig.aggregate(query);
  return storeConfig;
}

export async function aggregateStoreConfigWithPagination(query, options = {}) {
  const aggregate = StoreConfig.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const storeConfig = await StoreConfig.aggregatePaginate(aggregate, options);
  return storeConfig;
}
