/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { StoreNotification, Store } from 'models';

export async function getStoreNotificationById(id, options = {}) {
  const storeNotification = await StoreNotification.findById(id, options.projection, options);
  return storeNotification;
}

export async function getOne(query, options = {}) {
  const storeNotification = await StoreNotification.findOne(query, options.projection, options);
  return storeNotification;
}

export async function getStoreNotificationList(filter, options = {}) {
  const storeNotification = await StoreNotification.find(filter, options.projection, options);
  return storeNotification;
}

export async function getStoreNotificationListWithPagination(filter, options = {}) {
  const storeNotification = await StoreNotification.paginate(filter, options);
  return storeNotification;
}

export async function createStoreNotification(body, options = {}) {
  if (body.storeId) {
    const storeId = await Store.findOne({ _id: body.storeId });
    if (!storeId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field storeId is not valid');
    }
  }
  const storeNotification = await StoreNotification.create(body);
  return storeNotification;
}

export async function updateStoreNotification(filter, body, options = {}) {
  if (body.storeId) {
    const storeId = await Store.findOne({ _id: body.storeId });
    if (!storeId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field storeId is not valid');
    }
  }
  const storeNotification = await StoreNotification.findOneAndUpdate(filter, body, options);
  return storeNotification;
}

export async function updateManyStoreNotification(filter, body, options = {}) {
  const storeNotification = await StoreNotification.updateMany(filter, body, options);
  return storeNotification;
}

export async function removeStoreNotification(filter) {
  const storeNotification = await StoreNotification.findOneAndRemove(filter);
  return storeNotification;
}

export async function removeManyStoreNotification(filter) {
  const storeNotification = await StoreNotification.deleteMany(filter);
  return storeNotification;
}

export async function aggregateStoreNotification(query) {
  const storeNotification = await StoreNotification.aggregate(query);
  return storeNotification;
}

export async function aggregateStoreNotificationWithPagination(query, options = {}) {
  const aggregate = StoreNotification.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const storeNotification = await StoreNotification.aggregatePaginate(aggregate, options);
  return storeNotification;
}
