/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { UserAddress } from 'models';

export async function getUserAddressById(id, options = {}) {
  const userAddress = await UserAddress.findById(id, options.projection, options);
  return userAddress;
}

export async function getOne(query, options = {}) {
  const userAddress = await UserAddress.findOne(query, options.projection, options);
  return userAddress;
}

export async function getUserAddressList(filter, options = {}) {
  const userAddress = await UserAddress.find(filter, options.projection, options);
  return userAddress;
}

export async function getUserAddressListWithPagination(filter, options = {}) {
  const userAddress = await UserAddress.paginate(filter, options);
  return userAddress;
}

export async function createUserAddress(body, options = {}) {
  const userAddress = await UserAddress.create(body);
  return userAddress;
}

export async function updateUserAddress(filter, body, options = {}) {
  const userAddress = await UserAddress.findOneAndUpdate(filter, body, options);
  return userAddress;
}

export async function updateManyUserAddress(filter, body, options = {}) {
  const userAddress = await UserAddress.updateMany(filter, body, options);
  return userAddress;
}

export async function removeUserAddress(filter) {
  const userAddress = await UserAddress.findOneAndRemove(filter);
  return userAddress;
}

export async function removeManyUserAddress(filter) {
  const userAddress = await UserAddress.deleteMany(filter);
  return userAddress;
}

export async function aggregateUserAddress(query) {
  const userAddress = await UserAddress.aggregate(query);
  return userAddress;
}

export async function aggregateUserAddressWithPagination(query, options = {}) {
  const aggregate = UserAddress.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const userAddress = await UserAddress.aggregatePaginate(aggregate, options);
  return userAddress;
}
