/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import { UserDashboardConfig } from 'models';

export async function getUserDashboardConfigById(id, options = {}) {
  const userDashboardConfig = await UserDashboardConfig.findById(id, options.projection, options);
  return userDashboardConfig;
}

export async function getOne(query, options = {}) {
  const userDashboardConfig = await UserDashboardConfig.findOne(query, options.projection, options);
  return userDashboardConfig;
}

export async function getUserDashboardConfigList(filter, options = {}) {
  const userDashboardConfig = await UserDashboardConfig.find(filter, options.projection, options);
  return userDashboardConfig;
}

export async function getUserDashboardConfigListWithPagination(filter, options = {}) {
  const userDashboardConfig = await UserDashboardConfig.paginate(filter, options);
  return userDashboardConfig;
}

export async function createUserDashboardConfig(body, options = {}) {
  const userDashboardConfig = await UserDashboardConfig.create(body);
  return userDashboardConfig;
}

export async function updateUserDashboardConfig(filter, body, options = {}) {
  const userDashboardConfig = await UserDashboardConfig.findOneAndUpdate(filter, body, options);
  return userDashboardConfig;
}

export async function updateManyUserDashboardConfig(filter, body, options = {}) {
  const userDashboardConfig = await UserDashboardConfig.updateMany(filter, body, options);
  return userDashboardConfig;
}

export async function removeUserDashboardConfig(filter) {
  const userDashboardConfig = await UserDashboardConfig.findOneAndRemove(filter);
  return userDashboardConfig;
}

export async function removeManyUserDashboardConfig(filter) {
  const userDashboardConfig = await UserDashboardConfig.deleteMany(filter);
  return userDashboardConfig;
}

export async function aggregateUserDashboardConfig(query) {
  const userDashboardConfig = await UserDashboardConfig.aggregate(query);
  return userDashboardConfig;
}

export async function aggregateUserDashboardConfigWithPagination(query, options = {}) {
  const aggregate = UserDashboardConfig.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const userDashboardConfig = await UserDashboardConfig.aggregatePaginate(aggregate, options);
  return userDashboardConfig;
}
