/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { UserWishlist, Product } from 'models';

export async function getUserWishlistById(id, options = {}) {
  const userWishlist = await UserWishlist.findById(id, options.projection, options);
  return userWishlist;
}

export async function getOne(query, options = {}) {
  const userWishlist = await UserWishlist.findOne(query, options.projection, options);
  return userWishlist;
}

export async function getUserWishlistList(filter, options = {}) {
  const userWishlist = await UserWishlist.find(filter, options.projection, options);
  return userWishlist;
}

export async function getUserWishlistListWithPagination(filter, options = {}) {
  const userWishlist = await UserWishlist.paginate(filter, options);
  return userWishlist;
}

export async function createUserWishlist(body) {
  const { userId, productId } = body;

  // 🔍 Validate product
  const product = await Product.findById(productId);
  if (!product) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'Product not found');
  }

  // ❌ Prevent duplicate wishlist
  const alreadyExists = await UserWishlist.findOne({
    userId,
    productId,
    isDeleted: false,
  });

  if (alreadyExists) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'Product already added to wishlist');
  }

  // ✅ Create wishlist
  const userWishlist = await UserWishlist.create(body);
  return userWishlist;
}

export async function updateUserWishlist(filter, body, options = {}) {
  if (body.productId) {
    const productId = await Product.findOne({ _id: body.productId });
    if (!productId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productId is not valid');
    }
  }
  const userWishlist = await UserWishlist.findOneAndUpdate(filter, body, options);
  return userWishlist;
}

export async function updateManyUserWishlist(filter, body, options = {}) {
  const userWishlist = await UserWishlist.updateMany(filter, body, options);
  return userWishlist;
}

export async function removeUserWishlist(filter) {
  const userWishlist = await UserWishlist.findOneAndRemove(filter);
  return userWishlist;
}

export async function removeManyUserWishlist(filter) {
  const userWishlist = await UserWishlist.deleteMany(filter);
  return userWishlist;
}

export async function aggregateUserWishlist(query) {
  const userWishlist = await UserWishlist.aggregate(query);
  return userWishlist;
}

// export async function aggregateUserWishlistWithPagination(query, options = {}) {
//   const aggregate = UserWishlist.aggregate();
//   query.map((obj) => {
//     aggregate._pipeline.push(obj);
//   });
//   const userWishlist = await UserWishlist.aggregatePaginate(aggregate, options);
//   return userWishlist;
// }
