/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { UserCoupan, Product, Store } from 'models';

export async function getUserCoupanById(id, options = {}) {
  const userCoupan = await UserCoupan.findById(id, options.projection, options);
  return userCoupan;
}

export async function getOne(query, options = {}) {
  const userCoupan = await UserCoupan.findOne(query, options.projection, options);
  return userCoupan;
}

export async function getUserCoupanList(filter, options = {}) {
  const userCoupan = await UserCoupan.find(filter, options.projection, options);
  return userCoupan;
}

export async function getUserCoupanListWithPagination(filter, options = {}) {
  const userCoupan = await UserCoupan.paginate(filter, options);
  return userCoupan;
}

export async function createUserCoupan(body, options = {}) {
  if (body.productId) {
    const productId = await Product.find({ _id: { $in: body.productId } });
    if (productId.length !== body.productId.length) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productId is not valid');
    }
  }
  if (body.storeId) {
    const storeId = await Store.find({ _id: { $in: body.storeId } });
    if (storeId.length !== body.storeId.length) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field storeId is not valid');
    }
  }
  const userCoupan = await UserCoupan.create(body);
  return userCoupan;
}

export async function updateUserCoupan(filter, body, options = {}) {
  if (body.productId) {
    const productId = await Product.find({ _id: { $in: body.productId } });
    if (productId.length !== body.productId.length) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productId is not valid');
    }
  }
  if (body.storeId) {
    const storeId = await Store.find({ _id: { $in: body.storeId } });
    if (storeId.length !== body.storeId.length) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field storeId is not valid');
    }
  }
  const userCoupan = await UserCoupan.findOneAndUpdate(filter, body, options);
  return userCoupan;
}

export async function updateManyUserCoupan(filter, body, options = {}) {
  const userCoupan = await UserCoupan.updateMany(filter, body, options);
  return userCoupan;
}

export async function removeUserCoupan(filter) {
  const userCoupan = await UserCoupan.findOneAndRemove(filter);
  return userCoupan;
}

export async function removeManyUserCoupan(filter) {
  const userCoupan = await UserCoupan.deleteMany(filter);
  return userCoupan;
}

export async function aggregateUserCoupan(query) {
  const userCoupan = await UserCoupan.aggregate(query);
  return userCoupan;
}

export async function aggregateUserCoupanWithPagination(query, options = {}) {
  const aggregate = UserCoupan.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const userCoupan = await UserCoupan.aggregatePaginate(aggregate, options);
  return userCoupan;
}
