/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { Userlike, Product } from 'models';

export async function getUserlikeById(id, options = {}) {
  const userlike = await Userlike.findById(id, options.projection, options);
  return userlike;
}

export async function getOne(query, options = {}) {
  const userlike = await Userlike.findOne(query, options.projection, options);
  return userlike;
}

export async function getUserlikeList(filter, options = {}) {
  const userlike = await Userlike.find(filter, options.projection, options);
  return userlike;
}

export async function getUserlikeListWithPagination(filter, options = {}) {
  const userlike = await Userlike.paginate(filter, options);
  return userlike;
}

export async function createUserlike(body, options = {}) {
  if (body.productId) {
    const productId = await Product.findOne({ _id: body.productId });
    if (!productId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productId is not valid');
    }
  }
  const userlike = await Userlike.create(body);
  return userlike;
}

export async function updateUserlike(filter, body, options = {}) {
  if (body.productId) {
    const productId = await Product.findOne({ _id: body.productId });
    if (!productId) {
      throw new ApiError(httpStatus.BAD_REQUEST, 'field productId is not valid');
    }
  }
  const userlike = await Userlike.findOneAndUpdate(filter, body, options);
  return userlike;
}

export async function updateManyUserlike(filter, body, options = {}) {
  const userlike = await Userlike.updateMany(filter, body, options);
  return userlike;
}

export async function removeUserlike(filter) {
  const userlike = await Userlike.findOneAndRemove(filter);
  return userlike;
}

export async function removeManyUserlike(filter) {
  const userlike = await Userlike.deleteMany(filter);
  return userlike;
}

export async function aggregateUserlike(query) {
  const userlike = await Userlike.aggregate(query);
  return userlike;
}

export async function aggregateUserlikeWithPagination(query, options = {}) {
  const aggregate = Userlike.aggregate();
  query.map((obj) => {
    aggregate._pipeline.push(obj);
  });
  const userlike = await Userlike.aggregatePaginate(aggregate, options);
  return userlike;
}
