/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userController = require('./user.controller');
module.exports.userAddressController = require('./userAddress.controller');
module.exports.userDashboardConfigController = require('./userDashboardConfig.controller');
module.exports.productCategoriesController = require('./productCategories.controller');
module.exports.storeController = require('./store.controller');
module.exports.storeAddressController = require('./storeAddress.controller');
module.exports.businessCategoryController = require('./businessCategory.controller');
module.exports.sellerUserController = require('./sellerUser.controller');
module.exports.pickupAddressController = require('./pickupAddress.controller');
module.exports.bankDetailsController = require('./bankDetails.controller');
module.exports.productController = require('./product.controller');
module.exports.productTypeController = require('./productType.controller');
module.exports.productBrandController = require('./productBrand.controller');
module.exports.productVarientsController = require('./productVarients.controller');
module.exports.productVarientByProductIdController = require('./productVarientByProductId.controller');
module.exports.userlikeController = require('./userlike.controller');
module.exports.recentlyViewedController = require('./recentlyViewed.controller');
module.exports.reviewController = require('./review.controller');
module.exports.cartController = require('./cart.controller');
module.exports.coupanController = require('./coupan.controller');
module.exports.userCoupanController = require('./userCoupan.controller');
module.exports.userWishlistController = require('./userWishlist.controller');
module.exports.reviewReplyThreadController = require('./reviewReplyThread.controller');
module.exports.orderController = require('./order.controller');
module.exports.paymentController = require('./payment.controller');
module.exports.sellerPolicyController = require('./sellerPolicy.controller');
module.exports.inventoryController = require('./inventory.controller');
module.exports.inventoryAddressController = require('./inventoryAddress.controller');
module.exports.testController = require('./test.controller');
module.exports.storeNotificationController = require('./storeNotification.controller');
module.exports.storeConfigController = require('./storeConfig.controller');
module.exports.authController = require('./auth.controller');
module.exports.sellerAuthController = require('./sellerAuth.controller');
module.exports.bannerController = require('./banner.controller');
module.exports.CountryCodeController = require('./countryCode.controller');
