/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const CoupanSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    isActive: {
      type: Boolean,
      default: false,
    },
    minOrderValue: {
      type: Number,
    },
    maxCoupanAmount: {
      type: Number,
    },
    storeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Store',
    },
    product: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: 'Product',
    },
    coupanCode: {
      type: [String],
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
CoupanSchema.plugin(toJSON);
CoupanSchema.plugin(mongoosePaginateV2);
CoupanSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const CoupanModel = mongoose.models.Coupan || mongoose.model('Coupan', CoupanSchema, 'Coupan');
module.exports = CoupanModel;
