/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
const EnumCodeTypeOfCode = {
  RESET_LOGIN_CRED: 'resetLoginCred',
  RESETPASSWORD: 'resetPassword',
  LOGIN: 'login',
  MOBILE: 'mobile',
  EMAIL: 'email',
};
const EnumRoleOfUser = {
  USER: 'user',
  ADMIN: 'admin',
};
const EnumGenderOfUser = {
  MALE: 'male',
  FEMALE: 'female',
  OTHER: 'other',
};
const EnumPlatformOfDeviceToken = {
  ANDROID: 'android',
  IOS: 'ios',
  WEB: 'web',
};
const EnumBannerOfUserDashboardConfig = {
  PNG: 'png',
};
const EnumProfileImageOfStore = {
  PNG: 'png',
  JPG: 'jpg',
};
const EnumSettlementCycleOfStore = {
  WEEK: 'week',
  MONTH: 'month',
  QUATER: 'quater',
  YEAR: 'year',
  SIXMONTH: 'sixMonth',
};
const EnumProductImagesOfReview = {
  PNG: 'png',
  JPG: 'jpg',
};
const EnumPerformanceReportTimeOfStoreNotification = {
  WEEK: 'week',
  MONTH: 'month',
};
const EnumBannerOfStoreConfig = {
  PNG: 'png',
  JPG: 'jpg',
};
const EnumContentType = {
  IMAGE_PNG: 'image/png',
  IMAGE_JPEG: 'image/jpeg',
};
const EnumTypeOfToken = {
  RESET_PASSWORD: 'resetPassword',
  VERIFY_EMAIL: 'verifyEmail',
  REFRESH: 'refresh',
  SELLER_REFRESH: 'sellerRefresh',
};
const EnumOfImageTypes = {
  LISTING: 'listing',
  PROFILE_IMAGE: 'profileImage',
  STATUS_IMAGE: 'statusImage',
  PROFILE_VIDEO: 'profileVideo',
  BUSINESS_COVER: 'businessCover',
  SELLERSIGN: 'sellerSing',
  BANNER: 'banner',
};
const ProductVariantKeyEnum = {
  COLOR: 'color',
  SIZE: 'size',
  FABRIC: 'fabric',
  FIT: 'fit',
  PATTERN: 'pattern',
};
const ProductVariantValueEnum = {
  // COLORS
  RED: 'red',
  BLUE: 'blue',
  BLACK: 'black',
  WHITE: 'white',
  GREEN: 'green',

  // SIZES
  XS: 'xs',
  S: 's',
  M: 'm',
  L: 'l',
  XL: 'xl',
  XXL: 'xxl',

  // FABRIC
  COTTON: 'cotton',
  SILK: 'silk',
  POLYESTER: 'polyester',
  DENIM: 'denim',

  // FIT
  SLIM: 'slim',
  REGULAR: 'regular',
  LOOSE: 'loose',

  // PATTERN
  SOLID: 'solid',
  PRINTED: 'printed',
  CHECKED: 'checked',
};

module.exports = {
  EnumContentType,
  EnumCodeTypeOfCode,
  EnumRoleOfUser,
  EnumGenderOfUser,
  EnumPlatformOfDeviceToken,
  EnumBannerOfUserDashboardConfig,
  EnumProfileImageOfStore,
  EnumSettlementCycleOfStore,
  EnumProductImagesOfReview,
  EnumPerformanceReportTimeOfStoreNotification,
  EnumBannerOfStoreConfig,
  EnumTypeOfToken,
  EnumOfImageTypes,
  ProductVariantKeyEnum,
  ProductVariantValueEnum,
};
