/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports = {
  bannerOfUserDashboardConfig: {
    uploadServiceType: 'direct',
    allowedExtension: ['png'],
    allowedMaxFileSize: 50,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
  profileImageOfStore: {
    uploadServiceType: 'direct',
    allowedExtension: ['png', 'jpg'],
    allowedMaxFileSize: 10,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
  productImagesOfReview: {
    uploadServiceType: 'direct',
    allowedExtension: ['png', 'jpg'],
    allowedMaxFileSize: 25,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
  bannerOfStoreConfig: {
    uploadServiceType: 'direct',
    allowedExtension: ['png', 'jpg'],
    allowedMaxFileSize: 50,
    thumbnailResolutions: [],
    generateThumbnails: false,
  },
};
