/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const InventorySchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    store: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Store',
    },
    name: {
      type: String,
    },
    sourceType: {
      type: String,
    },
    productTitle: {
      type: String,
    },
    sourceAddressId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'InventoryAddress',
    },
    contactName: {
      type: String,
    },
    email: {
      type: String,
      // eslint-disable-next-line security/detect-unsafe-regex
      match: /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/,
    },
    mobileNumber: {
      type: Number,
    },
    countryCode: {
      type: String,
    },
    fax: {
      type: String,
    },
    latitude: {
      type: mongoose.Mixed,
    },
    longitude: {
      type: mongoose.Mixed,
    },
    priority: {
      type: Number,
    },
    status: {
      type: String,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
InventorySchema.plugin(toJSON);
InventorySchema.plugin(mongoosePaginateV2);
InventorySchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const InventoryModel = mongoose.models.Inventory || mongoose.model('Inventory', InventorySchema, 'Inventory');
module.exports = InventoryModel;
