/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const PickupAddressSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    storeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Store',
    },
    pincode: {
      type: Number,
      required: true,
    },
    addressLineOne: {
      type: String,
      required: true,
    },
    addessLineTwo: {
      type: String,
    },
    landmark: {
      type: String,
    },
    city: {
      type: String,
      required: true,
    },
    state: {
      type: String,
      required: true,
    },
    country: {
      type: String,
    },
    shopNo: {
      type: String,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
PickupAddressSchema.plugin(toJSON);
PickupAddressSchema.plugin(mongoosePaginateV2);
PickupAddressSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const PickupAddressModel =
  mongoose.models.PickupAddress || mongoose.model('PickupAddress', PickupAddressSchema, 'PickupAddress');
module.exports = PickupAddressModel;
