/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const ProductCategoriesSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    value: {
      type: String,
      required: true,
    },
    isSubCategory: {
      type: Boolean,
      default: false,
    },
    /**
     * this will be id if product category model id and this will come only if isSubCategory is true
     * */
    parentCategoryId: {
      type: String,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
ProductCategoriesSchema.plugin(toJSON);
ProductCategoriesSchema.plugin(mongoosePaginateV2);
ProductCategoriesSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const ProductCategoriesModel =
  mongoose.models.ProductCategories || mongoose.model('ProductCategories', ProductCategoriesSchema, 'ProductCategories');
module.exports = ProductCategoriesModel;
