/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
const OtherPolicyForStoreSchema = new mongoose.Schema({
  key: {
    type: String,
  },
  value: {
    type: String,
  },
});
const SellerPolicySchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    store: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Store',
    },
    privacy: {
      type: [String],
    },
    returnPolicy: {
      type: [String],
    },
    shipping: {
      type: [String],
    },
    other: {
      type: OtherPolicyForStoreSchema,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
SellerPolicySchema.plugin(toJSON);
SellerPolicySchema.plugin(mongoosePaginateV2);
SellerPolicySchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const SellerPolicyModel = mongoose.models.SellerPolicy || mongoose.model('SellerPolicy', SellerPolicySchema, 'SellerPolicy');
module.exports = SellerPolicyModel;
