/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import enumModel from 'models/enum.model';
import { toJSON, softDelete } from './plugins';

const StoreNotificationSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    storeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Store',
    },
    isSmsOn: {
      type: Boolean,
      default: true,
    },
    performanceReport: {
      type: Boolean,
      default: true,
    },
    emailNotification: {
      type: Boolean,
      default: true,
    },
    orderUpdates: {
      type: Boolean,
      default: true,
    },
    paymentUpdate: {
      type: Boolean,
      default: true,
    },
    lowStockAlerts: {
      type: Boolean,
      default: true,
    },
    performanceReportTime: {
      type: String,
      enum: Object.values(enumModel.EnumPerformanceReportTimeOfStoreNotification),
      default: enumModel.EnumPerformanceReportTimeOfStoreNotification.MONTH,
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
StoreNotificationSchema.plugin(toJSON);
StoreNotificationSchema.plugin(mongoosePaginateV2);
StoreNotificationSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const StoreNotificationModel =
  mongoose.models.StoreNotification || mongoose.model('StoreNotification', StoreNotificationSchema, 'StoreNotification');
module.exports = StoreNotificationModel;
