/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * If you want to add the new fields to your schema then go to the app.appinvento.io,
 * select your project then select model and click on + icon to add new fields.
 * For more checkout the docs at "docs.appinvento.io/product-guides/create-a-new-collection-field"
 */
import mongoose from 'mongoose';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
import { toJSON, softDelete } from './plugins';

const UserCoupanSchema = new mongoose.Schema(
  {
    /**
     * created By
     * */
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * updated By
     * */
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    /**
     * // this wil be in number, todo : update this model as per future plan
     * */
    coupanValue: {
      type: Number,
    },
    minOrderValue: {
      type: Number,
    },
    maxCoupanAmount: {
      type: Number,
    },
    coupenPercentage: {
      type: Number,
    },
    coupanCode: {
      type: String,
    },
    productId: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: 'Product',
    },
    storeId: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: 'Store',
    },
  },
  { timestamps: { createdAt: true, updatedAt: true } }
);
UserCoupanSchema.plugin(toJSON);
UserCoupanSchema.plugin(mongoosePaginateV2);
UserCoupanSchema.plugin(softDelete, {
  isSoftDeleteAddon: true,
  overrideMethods: 'all',
  deleted: 'isDeleted',
  deletedBy: 'deletedBy',
  deletedAt: 'deletedAt',
});
const UserCoupanModel = mongoose.models.UserCoupan || mongoose.model('UserCoupan', UserCoupanSchema, 'UserCoupan');
module.exports = UserCoupanModel;
